<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.opcua.arrow</groupId>
        <artifactId>opcua-arrow</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>opcua-arrow-test-server</artifactId>
    <packaging>jar</packaging>

    <!-- SOMENTE MILO SERVER + NETTY BOM -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>4.1.108.Final</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.milo</groupId>
            <artifactId>milo-sdk-server</artifactId>
            <version>1.0.8</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.11</version>
        </dependency>
    </dependencies>
</project>
